[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_cdt_bridge = "GJsfMLfg1tDdjCGJuKj92THEKgJQBgBQ7iQHYj9MA5Qu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/eren/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
